In [2]:
import sys
sys.path.append('../')
import torch
from transformer.layers import MultiHeadAttention, FeedForward, LayerNorm
from transformer.decoder import DecoderLayer, Decoder

# Define the dimensions,, dropout rate, and number of layers
d_model = 8 # feature dimension
h = 8 #  number of heads
dropout = 0.1 # dropout ratio
d_ff = 2048 # the dimension of the feed forward network
batch_size = 1 # batch size
seq_len = 4 # sequence length

num_layers = 6 # number of encoder layer

# Create an instance of the MultiHeadAttention and FeedForward classes
self_attention = MultiHeadAttention(d_model, h, dropout)
encoder_decoder_attention = MultiHeadAttention(d_model, h, dropout)
feed_forward = FeedForward(d_model, d_ff, dropout)  # 2048 is the dimension of the feed forward network

# Create an instance of the DecoderLayer class
decoder_layer = DecoderLayer(d_model, self_attention, encoder_decoder_attention, feed_forward, dropout)

# Create an instance of the Decoder class
decoder = Decoder(d_model, decoder_layer, num_layers)

# Create a random tensor to represent a batch of sequences
torch.manual_seed(68) # for reproducible result of random process
x = torch.rand(batch_size, seq_len, d_model) 
torch.manual_seed(101) # for reproducible result of random process
encoder_output = torch.rand(batch_size, seq_len, d_model) 

# Pass the tensor through the decoder
output = decoder(x, encoder_output)

print("Initial input tensor: \n", x)
print("Encoder output tensor: \n", encoder_output)
print("Output's shape: \n", output.shape)  
print("Output: \n", output) 

Initial input tensor: 
 tensor([[[0.3991, 0.5521, 0.1004, 0.2844, 0.9998, 0.7077, 0.8031, 0.2066],
         [0.3589, 0.8509, 0.8753, 0.4669, 0.6566, 0.6026, 0.2785, 0.1350],
         [0.2257, 0.9548, 0.8214, 0.1386, 0.6055, 0.2300, 0.7895, 0.4098],
         [0.0428, 0.4400, 0.2381, 0.4967, 0.8516, 0.4378, 0.4367, 0.0916]]])
Encoder output tensor: 
 tensor([[[0.1980, 0.4503, 0.0909, 0.8872, 0.2894, 0.0186, 0.9095, 0.3406],
         [0.4309, 0.7324, 0.4776, 0.0716, 0.5834, 0.7521, 0.7649, 0.1443],
         [0.7152, 0.3953, 0.6244, 0.3684, 0.8823, 0.3746, 0.1458, 0.3671],
         [0.5645, 0.5272, 0.1141, 0.0992, 0.1637, 0.7688, 0.4825, 0.8019]]])
Output's shape: 
 torch.Size([1, 4, 8])
Output: 
 tensor([[[-0.3688, -1.4840, -0.4858,  1.1288,  0.6073, -1.0262,  1.2634,
           0.3653],
         [-0.5547, -1.2814, -0.3132,  1.4950,  0.3125, -1.1744,  0.9710,
           0.5452],
         [-0.7233, -0.8057,  0.5567,  0.9686,  0.3816, -1.7979,  1.0208,
           0.3993],
         [-0.4538,