In [1]:
import numpy as np

def softmax(values):
    # Convert values to a numpy array
    values = np.array(values, dtype=float)
    
    # Compute the exponentials of the values
    exp_values = np.exp(values - np.max(values))
    
    # Compute the softmax
    softmax_values = exp_values / np.sum(exp_values)
    
    return softmax_values

In [4]:
values = [0.252, -np.inf]
softmax(values)

array([1., 0.])

In [7]:
values = [0.123, 0.264, -np.inf]
softmax(values)

array([0.46480828, 0.53519172, 0.        ])

In [8]:
values = [0.152, 0.134, 0.241, -np.inf]
softmax(values)

array([0.32517769, 0.31937686, 0.35544545, 0.        ])

In [9]:
values = [0.136,0.152,0.121,0.255, -np.inf]
softmax(values)

array([0.24227092, 0.24617843, 0.23866398, 0.27288668, 0.        ])

In [10]:
values = [0.164,0.141,0.106,0.184, 0.295]
softmax(values)

array([0.19680849, 0.19233356, 0.18571832, 0.20078429, 0.22435534])